version: '3.9'

services:
  schedule_be_nsgaii:
    build: .
    image: schedule_be_nsgaii:v4
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/code
    restart: unless-stopped